### PR TITLE
BICS Support

### PR DESCRIPTION
**Pull request by ryan-berger**

### CODE REVIEW

**Comment by regehr** [comment]
what's the status of this pull request @ryan-berger @nbushehri ?

**Comment by regehr** [comment]
please either finish it up, or close it if it's dead

**Comment by nbushehri** [comment]
Please update the pull request to include a few test cases in tests/arm-tv/ that make use of the newly added instruction

**Comment by ryan-berger** [comment]
These conflicts are too numerous. I'm going to checkout arm-tv-temp and copy paste the changes. I'll make sure we have test coverage as well.

**Comment by regehr** [comment]
yeah there's not much to your patch here so redoing it would be hardly any work. if you have time to support these instructions for real, great! I think they might be just about the only easy integer operations left.

**Comment by nbushehri** [comment]
@ryan-berger The current branch is arm-tv, not arm-tv-temp

**Comment by ryan-berger** [comment]
Closing this in favor of the other PR

**Pull request closed without merging**
